using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
public class ScriptsCamera : MonoBehaviour
{
    private bool camAvailable;
    private WebCamTexture backCam;
    private WebCamTexture frontCam;
    private Texture defaultBackground;

    public RawImage background;
    public AspectRatioFitter fit;

    // Use this for initialization
    private void Start()
    {
        defaultBackground = background.texture;
        WebCamDevice[] devices = WebCamTexture.devices;
        if (devices.Length == 0)
        {
            Debug.Log("No camera detected");
            camAvailable = false;
            return;
        }
        for (int i = 0; i < devices.Length; i++)
        {

            //            if (!devices [i].isFrontFacing) {    //開啟後鏡頭
            if (devices[i].isFrontFacing)
            {    //開啟前鏡頭
                backCam = new WebCamTexture(devices[i].name, Screen.width, Screen.height);
            }
        }
        if (backCam == null)
        {
            Debug.Log("Unable to find back camera");
            return;
        }
        backCam.Play();
        background.texture = backCam;

        camAvailable = true;
    }

    // Update is called once per frame
    private void Update()
    {
        if (varName.game1Over == true)
        {
            Debug.Log("遊戲結束關鏡頭");
            backCam.Stop();
        }
           
        if (!camAvailable)
            return;
        if (varName.game1Over == false)
        {
            Debug.Log("遊戲還沒結束");
            float ratio = (float)backCam.width / (float)backCam.height;
            fit.aspectRatio = ratio;

            float scaleY = backCam.videoVerticallyMirrored ? -1f : 1f;
            //        background.rectTransform.localScale = new Vector3 (1f, scaleY, 1f);    //非鏡像
            background.rectTransform.localScale = new Vector3(-1f, scaleY, 1f);    //鏡像

            int orient = -backCam.videoRotationAngle;
            background.rectTransform.localEulerAngles = new Vector3(0, 0, orient);

        }

    }
}